export const chats = [
  {
    id: 1,
    avatar: 'J',
    name: 'Joseph Yegorov',
    lastMessage: 'Изображение',
    unreadMessage: 5,
    createdAt: '08:24',
  },
  {
    id: 2,
    avatar: 'B',
    name: 'Boris Glazkov',
    lastMessage: 'Вы: стикер',
    unreadMessage: 2,
    createdAt: '04:22',
  },
  {
    id: 3,
    avatar: 'C',
    name: 'Capitolina Avdeyeva',
    lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!...',
    unreadMessage: 3,
    createdAt: '20:30',
  },
  {
    id: 4,
    avatar: 'I',
    name: 'Ildar Alekseeva',
    lastMessage: 'Вы: Круто!',
    unreadMessage: 1,
    createdAt: '16:55',
  },
  {
    id: 5,
    avatar: 'A',
    name: 'Artem Yevdokimov',
    lastMessage: 'И Human Interface Guidelines и Material Design рекомендуют...',
    unreadMessage: 1,
    createdAt: '14:27',
  },
  {
    id: 6,
    avatar: 'C',
    name: 'Chariton Gorbunov',
    lastMessage: 'Миллионы россиян ежедневно проводят десятки часов свое...',
    unreadMessage: 5,
    createdAt: '12:12',
  },
  {
    id: 7,
    avatar: 'E',
    name: 'Emmanuel Istomin',
    lastMessage: 'В 2008 году художник Jon Rafman  начал собирать...',
    unreadMessage: 1,
    createdAt: '21:12',
  },
  {
    id: 8,
    avatar: 'S',
    name: 'Susanna Yefimova',
    lastMessage: 'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
    unreadMessage: null,
    createdAt: '09:12',
  },
  {
    id: 9,
    avatar: 'E',
    name: 'Emma Ignatyeva',
    lastMessage: 'Можно или сегодня или завтра вечером.',
    unreadMessage: null,
    createdAt: '13:22',
  },
  {
    id: 10,
    avatar: 'U',
    name: 'Ustinov Bezrukova',
    lastMessage: 'Миллионы россиян ежедневно проводят десятки часов свое...',
    unreadMessage: null,
    createdAt: '00:22',
  },
  {
    id: 11,
    avatar: 'E',
    name: 'Eugene Agapova',
    lastMessage: 'Вы: стикер',
    unreadMessage: null,
    createdAt: '00:23',
  },
  {
    id: 12,
    avatar: 'O',
    name: 'Olga Alekseeva',
    lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!...',
    unreadMessage: null,
    createdAt: '01:24',
  },
  {
    id: 13,
    avatar: 'T',
    name: 'Trifon Kotov',
    lastMessage: 'Вы: стикер',
    unreadMessage: null,
    createdAt: '15:24',
  },
  {
    id: 14,
    avatar: 'A',
    name: 'Alex Andreev',
    lastMessage: 'Изображение',
    unreadMessage: null,
    createdAt: '13:01',
  },
  {
    id: 15,
    avatar: 'E',
    name: 'Emmanuel Repin',
    lastMessage: 'Можно или сегодня или завтра вечером.',
    unreadMessage: null,
    createdAt: '12:45',
  },
];
